//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contacto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CONTACTO
    {
        [DisplayName("Nombre")]
        public string NOMBRE { get; set; }

        [DisplayName("Apellido")]
        public string APELLIDO { get; set; }

        [DisplayName("Documento de Identidad")]
        public string DOCUMENTODEIDENTIDAD { get; set; }

        [DisplayName("Fecha de Creación")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FECHADECREACION { get; set; }

        [DisplayName("Motivo de Visita")]
        public string MOTIVODEVISITA { get; set; }

        [DisplayName("Fecha de Visita")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FECHADEVISITA { get; set; }

        [DisplayName("Hora de Entrada")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> HORADEENTRADA { get; set; }

        [DisplayName("Hora de Salida")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> HORADESALIDA { get; set; }

        [DisplayName("Persona que lo aistio")]
        public string PERSONAQUELOASISTIO { get; set; }
    }
}
